use_frameworks!

platform :ios, '8.0'

target 'FCCollectionViewLayout_Example' do
  pod 'FCCollectionViewLayout', :path => '../'

  target 'FCCollectionViewLayout_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
